services:
  api:
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
